spring.application.name=course-registrations

spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/course_registrations?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=app_user
spring.datasource.password=${COURSE_REG_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.initialization-fail-timeout=-1
